package com.test2.db.test2_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE RisorsaBase PLEASE EDIT ../Risorsa.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Risorsa object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;
import com.test2.db.test2_db.entity.Risorsa;
// Import relations

import com.test2.db.test2_db.entity.Tecnologia;



@MappedSuperclass
public class RisorsaBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column()
    private String nominativo;
	
	
	// Relations m:m tecnologie
	@ManyToMany()
	@JoinTable(name="Risorsa_Tecnologia",
		joinColumns = @JoinColumn(name="Risorsa_ID"),
		inverseJoinColumns = @JoinColumn(name="Tecnologia_ID")
			)
	private List<Tecnologia> tecnologie = new ArrayList<>();
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getNominativo() {
		return nominativo;
	}

	public void setNominativo(String nominativo) {
		this.nominativo = nominativo;
	}
    

    
	
	public List<Tecnologia> getTecnologie() {
		return this.tecnologie;
	}

	public void addTecnologie(Tecnologia Tecnologia) {
		this.tecnologie.add(Tecnologia);
	}

	public void setTecnologie(List<String> tecnologia) {
		this.tecnologie = tecnologia.stream()
			.map(id -> new Tecnologia(id))
			.collect(Collectors.toList());
	}

	public void removeTecnologie(Tecnologia Tecnologia) {
		this.tecnologie.remove(Tecnologia);
	}
	
}