/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE fornitoreBaseService PLEASE EDIT ../fornitore.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Fornitore } from '../../domain/test2_db/fornitore';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Fornitore.service.ts
 */

/*
 * SCHEMA DB Fornitore
 *
	{
		commerciale: {
			type: 'String'
		},
		nominativo: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		risorse: {
			type: Schema.ObjectId,
			ref : "Fornitore"
		},
	}
 *
 */
@Injectable()
export class FornitoreBaseService {

    contextUrl: string = environment.endpoint + '/fornitores';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * FornitoreService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Fornitore): Observable<Fornitore> {
        return this.http
            .post<Fornitore>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * FornitoreService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FornitoreService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Fornitore> {
        return this.http
            .get<Fornitore>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FornitoreService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Fornitore[]> {
        return this.http
            .get<Fornitore[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * FornitoreService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Fornitore): Observable<Fornitore> {
        return this.http
            .post<Fornitore>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
