/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE risorsaBaseService PLEASE EDIT ../risorsa.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Risorsa } from '../../domain/test2_db/risorsa';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Risorsa.service.ts
 */

/*
 * SCHEMA DB Risorsa
 *
	{
		nominativo: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		risorse: {
			type: Schema.ObjectId,
			ref : "Fornitore"
		},
		tecnologie: [{
			type: Schema.ObjectId,
			ref : "Risorsa"
		}],
	}
 *
 */
@Injectable()
export class RisorsaBaseService {

    contextUrl: string = environment.endpoint + '/risorsas';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * RisorsaService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Risorsa): Observable<Risorsa> {
        return this.http
            .post<Risorsa>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * RisorsaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * RisorsaService.findBytecnologie
    *   @description CRUD ACTION findBytecnologie
    *   @param Objectid key Id della risorsa tecnologie da cercare
    *
    */
    findByTecnologie(id: string): Observable<Risorsa[]> {
        return this.http
            .get<Risorsa[]>(this.contextUrl + '/findBytecnologie/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * RisorsaService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Risorsa> {
        return this.http
            .get<Risorsa>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * RisorsaService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Risorsa[]> {
        return this.http
            .get<Risorsa[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * RisorsaService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Risorsa): Observable<Risorsa> {
        return this.http
            .post<Risorsa>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
