/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE tecnologiaBaseService PLEASE EDIT ../tecnologia.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Tecnologia } from '../../domain/test2_db/tecnologia';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Tecnologia.service.ts
 */

/*
 * SCHEMA DB Tecnologia
 *
	{
		//RELATIONS
		//EXTERNAL RELATIONS
		tecnologie: [{
			type: Schema.ObjectId,
			ref : "Risorsa"
		}],
	}
 *
 */
@Injectable()
export class TecnologiaBaseService {

    contextUrl: string = environment.endpoint + '/tecnologias';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * TecnologiaService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Tecnologia): Observable<Tecnologia> {
        return this.http
            .post<Tecnologia>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * TecnologiaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TecnologiaService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Tecnologia> {
        return this.http
            .get<Tecnologia>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TecnologiaService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Tecnologia[]> {
        return this.http
            .get<Tecnologia[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * TecnologiaService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Tecnologia): Observable<Tecnologia> {
        return this.http
            .post<Tecnologia>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
