package com.test2.db.test2_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE RisorsaBaseDto PLEASE EDIT ../RisorsaDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Risorsa object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import com.test2.db.test2_db.entity.Risorsa;
// Import relations
import com.test2.db.test2_db.dtos.infos.FornitoreInfo;



import com.test2.db.test2_db.dtos.infos.TecnologiaInfo;


public class RisorsaBaseDto {
	
	private Long _id;
	
	// Attributes
    private String nominativo;
	
	// Relations Fornitore
	private List<Long> risorse_Fornitore = new ArrayList<>();
	
	
	// Relations m:m tecnologie
	private List<String> tecnologie = new ArrayList<>();
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getNominativo() {
		return nominativo;
	}

	public void setNominativo(String nominativo) {
		this.nominativo = nominativo;
	}
    
	// Relations Fornitore
	
	public List<Long> getrisorse_Fornitore() {
		return this.risorse_Fornitore;
	}

    public void setrisorse_Fornitore(List<FornitoreInfo> list) {
		this.risorse_Fornitore = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	

    
	
	public List<String> getTecnologie() {
		return this.tecnologie;
	}

	public void setTecnologie(List<TecnologiaInfo> tecnologie) {
		tecnologie.forEach(actor -> {
			this.tecnologie.add(String.valueOf(actor.get_id()));
		});
	}

	
}